/********************************************************************
* guiviewerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error guiviewerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableguiviewerDict();
extern void G__cpp_setup_inheritanceguiviewerDict();
extern void G__cpp_setup_typetableguiviewerDict();
extern void G__cpp_setup_memvarguiviewerDict();
extern void G__cpp_setup_globalguiviewerDict();
extern void G__cpp_setup_memfuncguiviewerDict();
extern void G__cpp_setup_funcguiviewerDict();
extern void G__set_cpp_environmentguiviewerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "guiviewer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__guiviewerDictLN_TClass;
extern G__linked_taginfo G__guiviewerDictLN_TBuffer;
extern G__linked_taginfo G__guiviewerDictLN_TMemberInspector;
extern G__linked_taginfo G__guiviewerDictLN_TObject;
extern G__linked_taginfo G__guiviewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__guiviewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__guiviewerDictLN_TList;
extern G__linked_taginfo G__guiviewerDictLN_TGObject;
extern G__linked_taginfo G__guiviewerDictLN_TQObject;
extern G__linked_taginfo G__guiviewerDictLN_TGWindow;
extern G__linked_taginfo G__guiviewerDictLN_TGFrame;
extern G__linked_taginfo G__guiviewerDictLN_TGCompositeFrame;
extern G__linked_taginfo G__guiviewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__guiviewerDictLN_TGMainFrame;
extern G__linked_taginfo G__guiviewerDictLN_TCanvas;
extern G__linked_taginfo G__guiviewerDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__guiviewerDictLN_TGaxis;
extern G__linked_taginfo G__guiviewerDictLN_TGDoubleSlider;
extern G__linked_taginfo G__guiviewerDictLN_Viewer;

/* STUB derived class for protected member access */
