/********************************************************************
* TetrisDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TetrisDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTetrisDict();
extern void G__cpp_setup_inheritanceTetrisDict();
extern void G__cpp_setup_typetableTetrisDict();
extern void G__cpp_setup_memvarTetrisDict();
extern void G__cpp_setup_globalTetrisDict();
extern void G__cpp_setup_memfuncTetrisDict();
extern void G__cpp_setup_funcTetrisDict();
extern void G__set_cpp_environmentTetrisDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Tetris.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TetrisDictLN_TClass;
extern G__linked_taginfo G__TetrisDictLN_TBuffer;
extern G__linked_taginfo G__TetrisDictLN_TMemberInspector;
extern G__linked_taginfo G__TetrisDictLN_TObject;
extern G__linked_taginfo G__TetrisDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TetrisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TetrisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TetrisDictLN_TQObject;
extern G__linked_taginfo G__TetrisDictLN_TAttPad;
extern G__linked_taginfo G__TetrisDictLN_TAttLine;
extern G__linked_taginfo G__TetrisDictLN_TAttFill;
extern G__linked_taginfo G__TetrisDictLN_TCanvas;
extern G__linked_taginfo G__TetrisDictLN_TVirtualPad;
extern G__linked_taginfo G__TetrisDictLN_TPad;
extern G__linked_taginfo G__TetrisDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TetrisDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TetrisDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TetrisDictLN_Tetris;
extern G__linked_taginfo G__TetrisDictLN_TetrisBoard;
extern G__linked_taginfo G__TetrisDictLN_CurrentPiece;
extern G__linked_taginfo G__TetrisDictLN_NextPiecePad;
extern G__linked_taginfo G__TetrisDictLN_QuitButton;
extern G__linked_taginfo G__TetrisDictLN_PauseButton;
extern G__linked_taginfo G__TetrisDictLN_NewGameButton;
extern G__linked_taginfo G__TetrisDictLN_InfoPad;
extern G__linked_taginfo G__TetrisDictLN_KeyHandler;
extern G__linked_taginfo G__TetrisDictLN_UpdateLevelTimer;

/* STUB derived class for protected member access */
