#
# Author: M. Kordosky
#
# a very simple makefile, which builds a shared library <package_name>.so
# from all the .C files in the package directory
#
# The only dependencies are on ROOT
#
# The shared library is deposited in the local (e.g. build) directory
# in principle it is better to move all libraries into one lib/ directory
# in a "make install" step but this makefile doesn't do that
#
#

package_name=rootana_utils

OPT           = 
CXXOPT        =
NOOPT         =
EXCEPTION     =
INCLUDES      = $(shell ${R10SYS}/utils/r10-config --include)
CXX           = g++ -m32
CXXFLAGS      = $(EXCEPTION) $(OPT) $(CXXOPT) -fPIC $(INCLUDES)
LD            = g++ -m32
LDFLAGS       = -shared
LDFLAGS2      = -static 
LIBS          = $(shell ${R10SYS}/utils/r10-config --libs)


# -- list here the single names of programs you want + .o

# make an object file <filename>.o out of each source file <filename>.c
objects = $(shell ls *.C | sed 's/.C/.o/') 

lib = lib$(package_name).so

lib2 = lib$(package_name).a

all : $(lib)
	gmake -C slim2
	gmake -C ana10

$(lib) : $(objects)

echo:
	@echo "objects: $(objects)"
	@echo "library: $(lib)"

mo100 : $(lib) mo100.o
#        @echo "<**Linking**> "$<
	$(LD)  mo100.o $(LIBS) $(R10LIBS) -o mo100

mo100.o : mo100.cpp
	@echo "<**Compiling**> "$<
	$(CXX) $(CXXFLAGS) -c $< -o  $@


%.o : %.C
	@echo "<**Compiling**> "$<
	$(CXX) $(CXXFLAGS) -c $< -o  $@

%.so :
	@echo "<**Linking**> " $@
	$(LD) $(LDFLAGS) $(objects) -o $@
	@mkdir -p lib
	@mv $@ $(R10SYS)/utils/lib

%.a :
	@echo "<**Linking**> " $@
	ar cru $@ $(objects) 
	@mkdir -p lib
	@mv $@ $(R10SYS)/utils/lib

# just remove the unnecessary object files
tidy:
	@rm -rf *.o

# remove the object files and the library
clean:
	@rm -rf *.o
	@rm -rf lib/*.so
	gmake clean -C slim2
	gmake clean -C ana10
