/********************************************************************
* AclockDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AclockDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableAclockDict();
extern void G__cpp_setup_inheritanceAclockDict();
extern void G__cpp_setup_typetableAclockDict();
extern void G__cpp_setup_memvarAclockDict();
extern void G__cpp_setup_globalAclockDict();
extern void G__cpp_setup_memfuncAclockDict();
extern void G__cpp_setup_funcAclockDict();
extern void G__set_cpp_environmentAclockDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Aclock.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AclockDictLN_TClass;
extern G__linked_taginfo G__AclockDictLN_TBuffer;
extern G__linked_taginfo G__AclockDictLN_TMemberInspector;
extern G__linked_taginfo G__AclockDictLN_TObject;
extern G__linked_taginfo G__AclockDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AclockDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AclockDictLN_TTimer;
extern G__linked_taginfo G__AclockDictLN_TQObject;
extern G__linked_taginfo G__AclockDictLN_TSysEvtHandler;
extern G__linked_taginfo G__AclockDictLN_TPad;
extern G__linked_taginfo G__AclockDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AclockDictLN_MinuteHand;
extern G__linked_taginfo G__AclockDictLN_HourHand;
extern G__linked_taginfo G__AclockDictLN_SecondHand;
extern G__linked_taginfo G__AclockDictLN_Aclock;

/* STUB derived class for protected member access */
