/********************************************************************
* HelloDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HelloDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableHelloDict();
extern void G__cpp_setup_inheritanceHelloDict();
extern void G__cpp_setup_typetableHelloDict();
extern void G__cpp_setup_memvarHelloDict();
extern void G__cpp_setup_globalHelloDict();
extern void G__cpp_setup_memfuncHelloDict();
extern void G__cpp_setup_funcHelloDict();
extern void G__set_cpp_environmentHelloDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Hello.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HelloDictLN_TClass;
extern G__linked_taginfo G__HelloDictLN_TBuffer;
extern G__linked_taginfo G__HelloDictLN_TMemberInspector;
extern G__linked_taginfo G__HelloDictLN_TObject;
extern G__linked_taginfo G__HelloDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HelloDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HelloDictLN_TList;
extern G__linked_taginfo G__HelloDictLN_TTimer;
extern G__linked_taginfo G__HelloDictLN_TQObject;
extern G__linked_taginfo G__HelloDictLN_TSysEvtHandler;
extern G__linked_taginfo G__HelloDictLN_TPad;
extern G__linked_taginfo G__HelloDictLN_Hello;

/* STUB derived class for protected member access */
