
/* Includes added by #pragma extra_include */
#include "vector"
/********************************************************************
* TrackMathCoreDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TrackMathCoreDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTrackMathCoreDict();
extern void G__cpp_setup_inheritanceTrackMathCoreDict();
extern void G__cpp_setup_typetableTrackMathCoreDict();
extern void G__cpp_setup_memvarTrackMathCoreDict();
extern void G__cpp_setup_globalTrackMathCoreDict();
extern void G__cpp_setup_memfuncTrackMathCoreDict();
extern void G__cpp_setup_funcTrackMathCoreDict();
extern void G__set_cpp_environmentTrackMathCoreDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TrackMathCore.h"

#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TrackMathCoreDictLN_ROOT;
extern G__linked_taginfo G__TrackMathCoreDictLN_string;
extern G__linked_taginfo G__TrackMathCoreDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMath;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLPositionVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEDouble32_tgRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLPositionVector3DlEROOTcLcLMathcLcLCartesian3DlEDouble32_tgRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO4cO4cOROOTcLcLMathcLcLMatRepStdlEdoublecO4cO4gRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO10gR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSMatrixlEDouble32_tcO4cO4cOROOTcLcLMathcLcLMatRepStdlEDouble32_tcO4cO4gRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSVectorlEDouble32_tcO10gR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO6cO6cOROOTcLcLMathcLcLMatRepSymlEdoublecO6gRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO21gR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSMatrixlEDouble32_tcO6cO6cOROOTcLcLMathcLcLMatRepSymlEDouble32_tcO6gRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_ROOTcLcLMathcLcLSVectorlEDouble32_tcO21gR;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackD;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackDcLcLdA;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackD32;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackD32cLcLdA;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackErrD;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackErrDcLcLdA;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackErrD32;
extern G__linked_taginfo G__TrackMathCoreDictLN_TrackErrD32cLcLdA;
extern G__linked_taginfo G__TrackMathCoreDictLN_VecTracklETrackDgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_vectorlETrackDcOallocatorlETrackDgRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_vectorlETrackDcOallocatorlETrackDgRsPgRcLcLiterator;
extern G__linked_taginfo G__TrackMathCoreDictLN_reverse_iteratorlEvectorlETrackDcOallocatorlETrackDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_VecTracklETrackDgRcLcLdA;
extern G__linked_taginfo G__TrackMathCoreDictLN_VecTracklETrackErrDgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_vectorlETrackErrDcOallocatorlETrackErrDgRsPgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_vectorlETrackErrDcOallocatorlETrackErrDgRsPgRcLcLiterator;
extern G__linked_taginfo G__TrackMathCoreDictLN_reverse_iteratorlEvectorlETrackErrDcOallocatorlETrackErrDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrackMathCoreDictLN_VecTracklETrackErrDgRcLcLdA;

/* STUB derived class for protected member access */
typedef VecTrack<TrackD> G__VecTracklETrackDgR;
typedef vector<TrackD,allocator<TrackD> > G__vectorlETrackDcOallocatorlETrackDgRsPgR;
typedef VecTrack<TrackErrD> G__VecTracklETrackErrDgR;
typedef vector<TrackErrD,allocator<TrackErrD> > G__vectorlETrackErrDcOallocatorlETrackErrDgRsPgR;
