/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux lxbuild148.cern.ch 2.6.18-92.1.18.el5 #1 SMP Wed Nov 12 06:45:11 EST 2008 x86_64 x86_64 x86_64 GNU/Linux" 
#define COMPILER "/usr/bin/g++34" 
#define COMPILERVERS "g++34"
#define MAKESHAREDLIB  "cd $BuildDir ; g++34 -c $Opt -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles ;  g++34 $ObjectFiles -shared -Wl,-soname,$LibName.so -m64 -O2  $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; g++34 -c  -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles; g++34 $ObjectFiles -m64 -O2  -o $ExeName $LinkedLibs -lm -ldl  -pthread -rdynamic"
#define CXXOPT "-O2"
#define CXXDEBUG "-g"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lCint -lMathCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o" 
#define SOEXT "so" 
